{% set name = "yfinance" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/subjectnull/yfinance
  git_rev: 4b4b02f131cd7d8975541a4d67d098895b6c51b9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - multitasking >=0.0.7
    - numpy >=1.15
    - pandas >=0.24
    - pip
    - python
    - requests >=2.20
  run:
    - multitasking >=0.0.7
    - numpy >=1.15
    - pandas >=0.24
    - python
    - requests >=2.20

test:
  imports:
    - yfinance

about:
  home: "https://github.com/subjectnull/yfinance"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "Yahoo! Finance market data downloader"
  description:
  doc_url: "https://github.com/subjectnull/yfinance"
  doc_source_url: https://github.com/subjectnull/yfinance/blob/master/README.rst


extra:
  recipe-maintainers:
    - subjectnull
